/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/TrendSenseNeonCore.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TrendSenseNeonCore.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NeonCore.geometry} material={materials.Mat_NeonCore} />
      <mesh geometry={nodes.GlassShell.geometry} material={materials.Mat_GlassShell} />
      <mesh geometry={nodes.DataRings.geometry} material={materials.Mat_DataRings} rotation={[Math.PI / 4, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/TrendSenseNeonCore.glb')
